//! Parser for `.PKGINFO` files.
//!
//! Format: `key = value` pairs, one per line.
//! Lines starting with `#` are comments. Multi-value fields appear as
//! repeated keys (e.g. multiple `depend = ...` lines).

use crate::error::XpmError;
use crate::package::types::PackageMeta;

// ── Public API ────────────────────────────────────────────────

/// Parse the raw bytes of a `.PKGINFO` file into a [`PackageMeta`].
pub fn parse_pkginfo(data: &[u8]) -> Result<PackageMeta, XpmError> {
    let text = std::str::from_utf8(data)
        .map_err(|e| XpmError::Package(format!("invalid UTF-8 in .PKGINFO: {e}")))?;

    let mut meta = PackageMeta::default();

    for line in text.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }

        let (key, value) = match line.split_once('=') {
            Some((k, v)) => (k.trim(), v.trim()),
            None => continue,
        };

        match key {
            "pkgname" => meta.name = value.to_string(),
            "pkgdesc" => meta.description = value.to_string(),
            "url" => meta.url = value.to_string(),
            "pkgver" => {
                // Format: "version-release" or just "version"
                if let Some((ver, rel)) = value.rsplit_once('-') {
                    meta.version = ver.to_string();
                    meta.release = rel.to_string();
                } else {
                    meta.version = value.to_string();
                    meta.release = "1".to_string();
                }
            }
            "builddate" => {
                meta.build_date = value.parse().unwrap_or(0);
            }
            "size" => {
                meta.installed_size = value.parse().unwrap_or(0);
            }
            "arch" => meta.arch.push(value.to_string()),
            "license" => meta.license.push(value.to_string()),
            "depend" => meta.depends.push(value.to_string()),
            "makedepend" => meta.makedepends.push(value.to_string()),
            "checkdepend" => meta.checkdepends.push(value.to_string()),
            "optdepend" => meta.optdepends.push(value.to_string()),
            "provides" => meta.provides.push(value.to_string()),
            "conflict" => meta.conflicts.push(value.to_string()),
            "replaces" => meta.replaces.push(value.to_string()),
            other => {
                meta.extra
                    .entry(other.to_string())
                    .or_default()
                    .push(value.to_string());
            }
        }
    }

    if meta.name.is_empty() {
        return Err(XpmError::Package(
            ".PKGINFO missing required field: pkgname".into(),
        ));
    }

    Ok(meta)
}

// ── Tests ─────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_pkginfo() -> &'static str {
        "# Generated by xpkg\n\
         pkgname = hello\n\
         pkgver = 1.0.0-1\n\
         pkgdesc = A hello world program\n\
         url = https://example.com\n\
         builddate = 1700000000\n\
         size = 12345\n\
         arch = x86_64\n\
         license = MIT\n\
         depend = glibc\n\
         depend = gcc-libs\n\
         optdepend = bash: for shell integration\n\
         provides = hello-world\n\
         conflict = hello-legacy\n"
    }

    #[test]
    fn parse_basic_pkginfo() {
        let meta = parse_pkginfo(sample_pkginfo().as_bytes()).unwrap();
        assert_eq!(meta.name, "hello");
        assert_eq!(meta.version, "1.0.0");
        assert_eq!(meta.release, "1");
        assert_eq!(meta.description, "A hello world program");
        assert_eq!(meta.url, "https://example.com");
        assert_eq!(meta.build_date, 1700000000);
        assert_eq!(meta.installed_size, 12345);
    }

    #[test]
    fn parse_multi_value_fields() {
        let meta = parse_pkginfo(sample_pkginfo().as_bytes()).unwrap();
        assert_eq!(meta.depends, vec!["glibc", "gcc-libs"]);
        assert_eq!(meta.arch, vec!["x86_64"]);
        assert_eq!(meta.license, vec!["MIT"]);
        assert_eq!(meta.provides, vec!["hello-world"]);
        assert_eq!(meta.conflicts, vec!["hello-legacy"]);
        assert_eq!(meta.optdepends, vec!["bash: for shell integration"]);
    }

    #[test]
    fn parse_version_without_release() {
        let data = "pkgname = test\npkgver = 2.0.0\n";
        let meta = parse_pkginfo(data.as_bytes()).unwrap();
        assert_eq!(meta.version, "2.0.0");
        assert_eq!(meta.release, "1");
    }

    #[test]
    fn parse_skips_comments_and_blanks() {
        let data = "# comment\n\npkgname = foo\n# another\npkgver = 1-1\n";
        let meta = parse_pkginfo(data.as_bytes()).unwrap();
        assert_eq!(meta.name, "foo");
    }

    #[test]
    fn parse_unknown_keys_go_to_extra() {
        let data = "pkgname = test\ncustom_field = hello\ncustom_field = world\n";
        let meta = parse_pkginfo(data.as_bytes()).unwrap();
        assert_eq!(
            meta.extra.get("custom_field").unwrap(),
            &vec!["hello".to_string(), "world".to_string()]
        );
    }

    #[test]
    fn missing_pkgname_returns_error() {
        let data = "pkgver = 1.0.0-1\n";
        let result = parse_pkginfo(data.as_bytes());
        assert!(result.is_err());
    }

    #[test]
    fn empty_input_returns_error() {
        let result = parse_pkginfo(b"");
        assert!(result.is_err());
    }

    #[test]
    fn parse_epoch_version() {
        let data = "pkgname = test\npkgver = 1:2.3.4-5\n";
        let meta = parse_pkginfo(data.as_bytes()).unwrap();
        assert_eq!(meta.version, "1:2.3.4");
        assert_eq!(meta.release, "5");
    }
}
